"""Initializaion AUTH 1.5

Revision ID: 0c7d797c0b3f
Revises: bdb9f0957f84
Create Date: 2023-06-27 03:10:00.812067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7d797c0b3f'
down_revision = 'bdb9f0957f84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
