"""Initializaion AUTH 1.2

Revision ID: 3b6cbd78b962
Revises: edd1d4c2ccc8
Create Date: 2023-06-27 02:36:54.881773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6cbd78b962'
down_revision = 'edd1d4c2ccc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
