"""empty message

Revision ID: 6bdf2af89b7e
Revises: 0c7d797c0b3f
Create Date: 2023-06-28 23:29:12.044245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdf2af89b7e'
down_revision = '0c7d797c0b3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PersProgram', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_column('PersProgram', 'file_pr')
    op.add_column('user', sa.Column('special_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'special_key')
    op.add_column('PersProgram', sa.Column('file_pr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('PersProgram', 'file_path')
    # ### end Alembic commands ###
