"""DATABASE TEST 2

Revision ID: a3d384c186c8
Revises: 949e27a08407
Create Date: 2023-06-26 23:12:59.923854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d384c186c8'
down_revision = '949e27a08407'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('diploms', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PersPrograms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_pr', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PersPrograms')
    op.drop_table('trainers')
    # ### end Alembic commands ###
