"""Initializaion AUTH 1.1

Revision ID: edd1d4c2ccc8
Revises: dd156305e815
Create Date: 2023-06-27 01:23:52.790919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edd1d4c2ccc8'
down_revision = 'dd156305e815'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PersPrograms')
    op.drop_table('trainers')
    op.drop_table('users')


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PersPrograms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"PersPrograms_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_pr', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trainer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='PersPrograms_client_id_fkey'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name='PersPrograms_trainer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='PersPrograms_pkey')
    )
    op.create_table('trainers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diploms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['users.id'], name='trainers_usr_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trainers_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_create', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_enter', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    # ### end Alembic commands ###
